### ISSUE TITLE
Add an option to show the MIR

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-playpen#154]
I think it would be awesome if Rust Playpen could display the MIR of the code - that is, the MIR generated for every single function, and (potentially) the tables that are kept around, storing information about types. (I know very little about what information is actually kept around besides the MIR code itself.)

With the MIR becoming a central piece of the compiler, and borrow checking determined to be performed on the MIR eventually, I think this will be a great tool to debug borrowck issues, and to learn more about what happens "behind the scenes", about all the desugaring that's going on. The LLVM IR is so low-level that much of this can't be seen anymore.

**Comment by jonas-schievink** [comment]
:+1: MIR now has a textual representation which could be dumped for an entire crate (needs a new `--unpretty` option?), so this should fit in nicely with the other formats.
