### ISSUE TITLE
Current Nightly output is garbled

### ISSUE THREAD

**Issue by mitaa** [rust-lang/rust-playpen#157]
[playpen](https://play.rust-lang.org/?code=fn%20main%28%29%20{%0A%20%20%20%20let%20unused%20%3D%207%3B%0A}&version=nightly)
```rust
fn main() {
    let unused = 42;
}
```
```
<anon>:2:9: 2:15 [33mwarning: (B[0m[1munused variable: `unused`, #[warn(unused_variables)] on by default(B[0m
<anon>:2     let unused = 42;
                 [33m^~~~~~(B[0m
```
Output of stable and beta looks normal.

**Comment by durka** [comment]
This ticket is closed, but the fix isn't rolled out to the site yet.

**Comment by alexcrichton** [comment]
Hm, how are you testing? It looks good to me?

![https://i.imgur.com/srSpbmQ.png](https://i.imgur.com/srSpbmQ.png)

**Comment by durka** [comment]
Huh, just caching problems, I guess.
