### ISSUE TITLE
Playground is broken in Safari

### ISSUE THREAD

**Issue by ChrisBuchholz** [rust-lang/rust-playpen#160]
The playground seems to be completely broken in Safari 9.0.2.

Code is not being evaluated, or if it is, the panel with the result is not being shown in any case.

I don't feel this issue needs any more details. It's just broken.

**Comment by nwin** [comment]
It is not completely broken. You “just” have to scroll down to see it. Can’t see the exact reason for this immediately.

**Comment by ChrisBuchholz** [comment]
@nwin: Try giving it a few tries. I thought I experienced that behavior where the "result panel" was just hidden out of sight and I had to scroll, but when I posted this issue, and still, if I go and try it out now, I can't even scroll down to see the result.

**Comment by killercup** [comment]
I think this is addressed by #167.

**Comment by alexcrichton** [comment]
Fixed by https://github.com/rust-lang/rust-playpen/pull/167, thanks @killercup!
