### ISSUE TITLE
usize doesn't get colored like u64 does

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust-playpen#161]
Since it's numeric, it should get colored blue

![screen shot 2015-12-14 at 9 40 14 am](https://cloud.githubusercontent.com/assets/416575/11783750/c8d6d4e8-a246-11e5-95c0-4aa24f26b23f.png)
![screen shot 2015-12-14 at 9 40 31 am](https://cloud.githubusercontent.com/assets/416575/11783751/c8db0158-a246-11e5-9d94-513c0ee3d95a.png)

**Comment by durka** [comment]
fixed now
