### ISSUE TITLE
output colors broken on beta and nightly

### ISSUE THREAD

**Issue by durka** [rust-lang/rust-playpen#174]
stable:
![stable](http://www.seas.upenn.edu/~aburka/tmp/Screen%20Shot%202016-01-27%20at%205.07.33%20PM.png)

beta:
![beta](http://www.seas.upenn.edu/~aburka/tmp/Screen%20Shot%202016-01-27%20at%205.09.17%20PM.png)

nightly:
![nightly](http://www.seas.upenn.edu/~aburka/tmp/Screen%20Shot%202016-01-27%20at%205.09.50%20PM.png)

**Comment by nrc** [comment]
There have been more than a few changes to diagnostics in rustc, but the colouring on the terminal is still OK. Looking through the playpen source I don't see anywhere obvious this could be going wrong.

**Comment by durka** [comment]
I was going to try to inspect the color codes that rustc produces, but I can't convince it to show them to me at all:

    TERM=xterm rustc foo.rs --color always 2>&1 | xxd

this produces no color codes in the output, on any release channel. Confusing.

**Comment by nrc** [comment]
I wonder if that broke as part of the diagnostics work. Would that cause this breakage? Looks like it might from the source code, but I don't really understand it.

Ah, but I would expect this to work on the release channel, if that were the case.

**Comment by durka** [comment]
If you look in the network console, it's simply not sending any color codes in the compiler output for beta and nightly. Did something change in how it process `$TERM`? I seem to remember that libterm was updated.

**Comment by durka** [comment]
Sorry, it does produce colors on stable, I was wrong before. So something changed such that after 1.6.0 rustc checks for a terminal and can't be convinced to print colors to a non-terminal. This seems like a bug, anyway, since `--color=always` exists.

**Comment by TimNN** [comment]
I'm pretty sure that rust-lang/rust#29999 inadvertently brought this to light since it somehow changed how `term::stderr()` works: colours will only be used when destination is a `Terminal`, which is only the case if `term::stderr()` returns `Some(_)` (see [emitter.rs:686](https://github.com/rust-lang/rust/blob/master/src/libsyntax/errors/emitter.rs#L686)).

**Comment by respeccing** [comment]
Looks like this got fixed and is no longer and issue.

https://play.rust-lang.org/?gist=2f5920fe579ff82b69b87b94b8727d7f&version=stable&backtrace=0
![screenshot_2016-04-03_06-32-50](https://cloud.githubusercontent.com/assets/17984080/14230775/00e48620-f966-11e5-96f0-a2bd61c0026a.png)
![screenshot_2016-04-03_06-33-00](https://cloud.githubusercontent.com/assets/17984080/14230776/046fe208-f966-11e5-976d-7fcce61505b5.png)
![screenshot_2016-04-03_06-33-08](https://cloud.githubusercontent.com/assets/17984080/14230777/068235a0-f966-11e5-990d-97565c8b741a.png)

**Comment by alexcrichton** [comment]
Indeed! (I believe this was fixed)
