### ISSUE TITLE
playbot on IRC has been down for a long time

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust-playpen#186]
For over two months now, `playbot-veno` has worked as a replacement, but it'd be good to get `playbot` and `playbot-mini` running again.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Yeah unfortunately I don't know what's going on here and I haven't had time to investigate yet, I'll see if I can get around to it though.

**Comment by alexcrichton** [comment]
Ok, think I figured it out, should be back now
