### ISSUE TITLE
Identifiers ending with digits are highlighted as 2 separate parts.

### ISSUE THREAD

**Issue by Enamex** [rust-lang/rust-playpen#201]
If an identifier ends with a digit (not followed by any letter or underscore), the digit is highlighted separately from the rest of the identifier.

_Also, slightly unrelated request: the keywords 'mut' and 'self' being the same color as all others in the middle of code is a worse situation that it'd been before ('self' and 'mut' were turquoise in Monokai, while now they're the same red shade as all others)._

**Comment by jonas-schievink** [comment]
You might want to report this to Ace (the editor used by the playpen): https://github.com/ajaxorg/ace

**Comment by Enamex** [comment]
Is this common procedure? Since this's a Rust-specific issue, so maybe a maintainer reporting it would push things faster.

[This issue](https://github.com/ajaxorg/ace/issues/2234) is still true.

**Comment by jonas-schievink** [comment]
I'm not sure, but there's not much that can be done in this repo, so opening an issue upstream at all can get it fixed faster

**Comment by TimNN** [comment]
I submitted a fix for this as ajaxorg/ace#3083

**Comment by TimNN** [comment]
The upstream fix has been accepted, we now need to 

a) either wait for a new version of ace to be released (which may take several months, looking at the schedule of previous releases) or
b) build a version of ace ourselves.
