### ISSUE TITLE
nightly execution fails sporadically

### ISSUE THREAD

**Issue by alexandermerritt** [rust-lang/rust-playpen#203]
Selecting nightly then Run results in

`playpen: mounting root-nightly as root-nightly (bind) failed: No such file or directory`
`playpen: application terminated with error code 1`

Using Chrome 50.0.2661.86 (64-bit) on OS X 10.11.4

**Comment by durka** [comment]
s/sporadically/consistently/

**Comment by alexcrichton** [comment]
I believe this has since been fixed.
