### ISSUE TITLE
All rust versions on playpen are at least one release behind.

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust-playpen#215]
Playpen currently runs

Stable: `rustc 1.8.0 (db2939409 2016-04-11)`
Beta: `rustc 1.9.0-beta.3 (e4e8b6668 2016-05-18)`
Nightly: `rustc 1.10.0-nightly (9c6904ca1 2016-05-18)`

As of today (2016-06-20), the latest versions are:

Stable: `rustc 1.9.0 (e4e8b6668 2016-05-18)`
Beta: `rustc 1.10.0-beta.2 (39f3c16cc 2016-05-26)`
Nightly: `rustc 1.11.0-nightly (bb4a79b08 2016-06-15)`

---
Original post:

Try running ([playpen](https://is.gd/hPE8Vk)):

```rust
#![feature(rustc_private)]
extern crate rustc_driver;

fn main() {
    println!("{:?}", rustc_driver::commit_date_str());
}
```

This prints: `Some("2016-05-18")`

**Comment by alexcrichton** [comment]
Logs indicate that we can't `cargo install rustfmt`:

```
May 31 16:56:50 ip-10-202-160-170.us-west-1.compute.internal init.sh[17637]: Updating registry `https://github.com/rust-lang/crates.io-index`
May 31 16:56:50 ip-10-202-160-170.us-west-1.compute.internal init.sh[17637]: error: failed to fetch `https://github.com/rust-lang/crates.io-index`
May 31 16:56:50 ip-10-202-160-170.us-west-1.compute.internal init.sh[17637]: Caused by:
May 31 16:56:50 ip-10-202-160-170.us-west-1.compute.internal init.sh[17637]: [16/-17] The SSL certificate is invalid
May 31 16:56:50 ip-10-202-160-170.us-west-1.compute.internal systemd[1]: rust-playpen-update.service: main process exited, code=exited, status=101/n/a
May 31 16:56:50 ip-10-202-160-170.us-west-1.compute.internal systemd[1]: Failed to start Playpen sandbox root updater.
May 31 16:56:50 ip-10-202-160-170.us-west-1.compute.internal systemd[1]: Unit rust-playpen-update.service entered failed state.
May 31 16:56:50 ip-10-202-160-170.us-west-1.compute.internal systemd[1]: rust-playpen-update.service failed.
```

No idea why :(

**Comment by jonas-schievink** [comment]
It works on my local system, so the server might just be missing a little

    roses are red
    violets are blue
    sudo pacman -Syu

**Comment by petrochenkov** [comment]
The nightly is one month old now.
Playpen must be hosted in some polar region.

**Comment by TimNN** [comment]
By the way, a better script to find the rust version used on playpen, which works on stable and beta is well is:

```
use std::process::Command;
use std::str;

fn main() {
    println!("{}", str::from_utf8(&Command::new("rustc").arg("-v").arg("-V").output().unwrap().stdout).unwrap());
}
```

At this point it is probably important to note that not only nightly but is outdated on playpen, but that stable and beta are also one version behind.

**Comment by alexcrichton** [comment]
Ok, as @eddyb pointed out I've [disabled rustfmt](https://github.com/rust-lang/rust-playpen/issues/216) to at least get these updated for now. Hopefully we can invest in a better solution soon.
