### ISSUE TITLE
Shorten and Gist buttons currently do nothing

### ISSUE THREAD

**Issue by solson** [rust-lang/rust-playpen#217]
Since the most recent update (earlier today), these buttons are non-functional.

**Comment by ActualizeInMaterial** [comment]
Perhaps the button can be allowed to exist but be hidden? as opposed to [inexistent](https://github.com/rust-lang/rust-playpen/commit/eacc8fb2886d950e870afb7b7c4726d2c4571c44#diff-1379b4aba232817d97dbd4fef2d0fc40R33) (I don't know yet if this is possible, my knowledge is limited, but I could probably look it up)
