### ISSUE TITLE
playbot IRC attributes no longer work

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust-playpen#220]
Apparently the README claims that things like `~mini` and `~nightly` work, but they aren't currently implemented in the Rust rewrite. Maybe they wouldn't be too hard though?

cc @jonas-schievink

**Comment by jonas-schievink** [comment]
Ah these actually didn't exist in the python version. I've implemented them in #187, but then removed them to keep the same interface.

**Comment by alexcrichton** [comment]
Ah ok, I'll leave this open to update the README then

**Comment by alexcrichton** [comment]
Ok, updated README
