### ISSUE TITLE
Waiting for play.rust-lang.org ...

### ISSUE THREAD

**Issue by ActualizeInMaterial** [rust-lang/rust-playpen#223]
Is it down or stuck perhaps?

ok it now said, after like 1min:
502 Bad Gateway

nginx/1.4.6 (Ubuntu)

I guess that means it's not stuck somewhere in Rust code...

url: https://play.rust-lang.org/?code=fn%20main()%20%7B%0A%20%20%20%20println!(%22Hello%2C%20world!%22)%3B%0A%7D%0A

**Comment by alexcrichton** [comment]
Should be back!
