### ISSUE TITLE
Playbot crashes difficult to debug

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust-playpen#225]
Right now if any thread in playbot crashes (e.g. panics) then the rest of the connections keep going and the logs have to be hunted through to find the culprit. Perhaps some tweaks could be done to assist this?

* For all programs run, debug the name of the channel as well
* Kill the entire process whenever a thread panics

Thoughts @jonas-schievink?

**Comment by brson** [comment]
If it could catch those panics and render an error page it would make it easier for users to submit bug reports.

**Comment by jonas-schievink** [comment]
@brson I think this is only about rustbot, the IRC bot, not the playpen webserver, but that idea sounds good anyways.

@alexcrichton Agreed. We should also set the name of the threads to the channel they're connected to (we don't do that currently for some reason). Maybe a viable (and very simple) way of implementing the second point would be to use the panic-as-abort machinery (unless I'm missing something).

**Comment by alexcrichton** [comment]
@jonas-schievink sounds good to me!

**Comment by jonas-schievink** [comment]
On the other hand, we probably don't want to make the playpen webserver DoS-prone by aborting on panics (Iron catches them for us, and there's a few places where wrong user input leads to a panic), and there's no way to make playbot abort on panic and playpen not. I'll make playbot abort in a `catch_unwind` block instead.
