### ISSUE TITLE
The Backtrace setting has no effect

### ISSUE THREAD

**Issue by icanrealizeum** [rust-lang/rust-playpen#229]
Try running [this code](https://play.rust-lang.org/?code=fn%20main()%20%7B%0A%20%20%20%20fn%20diverges()%20-%3E%20!%20%7B%0A%20%20%20%20%20%20%20%20panic!(%22This%20function%20never%20returns!%22)%3B%0A%20%20%20%20%7D%0A%20%20%20%20diverges()%3B%0A%7D&version=stable&backtrace=1)

You get the message: `note: Run with RUST_BACKTRACE=1 for a backtrace.`
even though the Backtrace setting is `on`

**Comment by jonas-schievink** [comment]
Ah, that's not implemented yet in the Rust version
