### ISSUE TITLE
Playbot crash on nick oddness

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust-playpen#231]
from syslog:

```
Jul 11 09:11:51 ip-10-235-19-101 playbot: thread '"playbot-mini"@irc.mozilla.org' panicked at 'All specified nicknames were in use or disallowed.', /home/ubuntu/.cargo/registry/src/github.com-88ac128001ac3a9a/irc-0.11.3/src/client/server/mod.rs:306
Jul 11 09:11:51 ip-10-235-19-101 playbot: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Jul 11 09:11:51 ip-10-235-19-101 playbot: ERROR:playbot: killing playbot due to previous error
```

**Comment by alexcrichton** [comment]
cc @jonas-schievink

**Comment by jonas-schievink** [comment]
Wait, so the `"` are part of the nick? I hope that's just a misconfiguration :sweat_smile:  (if so, playbot should crash immediately upon startup)

**Comment by alexcrichton** [comment]
I don't think they're configured as such:

```toml
[[server]]
nicks = ["playbot", "playbot-mini"]
```

perhaps that's just the panic message using `{:?}`?

**Comment by jonas-schievink** [comment]
Well, it's the thread name, which isn't formatted using `{:?}`. Does it crash immediately when starting or only after someone tries to talk to it?

**Comment by alexcrichton** [comment]
Nah this was a much delayed crash, and I think that the mozilla IRC servers were having trouble at the time (my client was disconnected at least). I don't know exactly what happened though unfortunately.

**Comment by alexcrichton** [comment]
The quotes are coming from [here](https://github.com/rust-lang/rust-playpen/blob/master/src/bin/playbot.rs#L257) where `name` has type `toml::Value` which when printed quotes strings, it's not literally being passed to the IRC server with quotes I believe.

**Comment by jonas-schievink** [comment]
Ah, that makes sense. If the IRC server was having trouble then maybe it thought that `playbot-mini` was still on the server when it tried to join.

I don't know much about IRC, but I'll try setting [`should_ghost`](http://aatxe.github.io/irc/irc/client/data/config/struct.Config.html#structfield.should_ghost), that sounds like it'll kick the old account.
