### ISSUE TITLE
backtrace=1 causes 500 Server error

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust-playpen#245]
Attempting to run any code on play.rust-lang.org (even just `fn main() {}`) returns a `500 Server Error` when a backtrace has been requested.

I cannot reproduce this error locally.

@alexcrichton: could you see if there is anything useful in the logs?

**Comment by alexcrichton** [comment]
Perhaps this is relevant?

```
Aug 28 18:09:56 ip-10-235-19-101 playpen: flag provided but not defined: -eRUST_BACKTRACE
Aug 28 18:09:56 ip-10-235-19-101 playpen: See 'docker create --help'.
```

Looks like some argument may not be getting passed correctly?

**Comment by alexcrichton** [comment]
Or maybe docker versions are different?

**Comment by TimNN** [comment]
Yeah, that was my first intuition, that some docker version did not accept the -e flag. Sadly I could not find anything relevant in their changelog :(

Do you know which docker version is running on playpen?

**Comment by alexcrichton** [comment]
Sure:

```
$ docker --version
Docker version 1.11.2, build b9f10c9
```

**Comment by TimNN** [comment]
Alright I found the problem (I think).

Basically, docker 1.12 got smarter when parsing flags: `-eFOO=BAR` is treated as "set flag `-eFOO` to value `BAR`" in 1.11 and as "set flag `-e` to value `FOO=BAR`" in docker 1.12.

I'll submit a fix soon.

**Comment by alexcrichton** [comment]
Thanks @TimNN!

**Comment by TimNN** [comment]
The fix seems to have worked, backtraces are now functional on http://play.rust-lang.org.
