### ISSUE TITLE
nightly is outdated again

### ISSUE THREAD

**Issue by durka** [rust-lang/rust-playpen#247]
I don't know how to find out which nightly it is, but rust-lang/rust#35869 isn't fixed.

**Comment by TimNN** [comment]
The nightly is `rustc 1.13.0-nightly (499484f56 2016-08-18)`

(By the way, this is a handy snippet to find the rust versions running on playpen:)

```rust
use std::process::Command;
use std::str;

fn main() {
    println!("{}", str::from_utf8(&Command::new("rustc").arg("-vV").output().unwrap().stdout).unwrap());
}
```

**Comment by alexcrichton** [comment]
Looks like the disk filled up with docker images, I've cleaned it out and we should be good to go now.
