### ISSUE TITLE
PR #248 not fully deployed (or broken)

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust-playpen#252]
PR #248 executed `rustc --version` before each invocation of the compiler.

This worked fine locally and I think I have seen it working once on https://play.rust-lang.org/ (although I've not been using / checking that often).

The only think that I can imagine going wrong is the docker images being build from an outdated repository checkout.

cc @alexcrichton.

**Comment by alexcrichton** [comment]
Oh I think I just forgot to deploy, deployed now though!
