### ISSUE TITLE
Playbot outputting rustc version

### ISSUE THREAD

**Issue by programble** [rust-lang/rust-playpen#253]
Looks like this recent commit https://github.com/rust-lang/rust-playpen/commit/320e9aa86b940c97dd32d8689d6b5b9e0c152121 now causes `playbot` to *always* output the version, which is unnecessary and just adds noise.

```
[17:17:57]  <dikaiosune>	playbot: '#'
[17:18:00] -playbot-	rustc 1.11.0 (9b21dcd6a 2016-08-15)
[17:18:00] -playbot-	'#'
```

**Comment by alexcrichton** [comment]
cc @TimNN, maybe playbot could be special cased?

**Comment by alexcrichton** [comment]
also cc https://github.com/rust-lang/rust-playpen/pull/248

**Comment by TimNN** [comment]
Yeah, I noticed that as well yesterday on IRC.

My proposed solution would be to set an environment variable (something like `RUST_PLAYPEN_ENV=web|irc`) and check that in the shell scripts.

I can submit a fix later today, unless someone else wants to.
