### ISSUE TITLE
Playground hasn't updated nightly in two weeks

### ISSUE THREAD

**Issue by Thinkofname** [rust-lang/rust-playpen#258]
Nightly builds have been a bit spotty lately but there have been a few successful ones in between. The playground however doesn't seem to be picking them up.

Its on `rustc 1.14.0-nightly (6e8f92f11 2016-10-07)` whilst the last good one was `rustc 1.14.0-nightly (f09420685 2016-10-20)`

**Comment by alexcrichton** [comment]
I cleaned a bit out and I think they'll update tomorrow night, we'll see though.

**Comment by Thinkofname** [comment]
`rustc 1.14.0-nightly (3caf63cc0 2016-10-24)` Seems fixed!
