### ISSUE TITLE
MIR display doesn't work

### ISSUE THREAD

**Issue by Songbird0** [rust-lang/rust-playpen#289]
Hi there !

I'm trying to compile a code example from RustByExample book on playpen, but it doesn't work. Display is like "frozen".

Here's what happens when clicking `MIR` button:

![mircrashed](https://cloud.githubusercontent.com/assets/13397428/26705239/3ce1f02c-4735-11e7-9ae1-67a7dd365731.png)

Browser: `Firefox 53.03`.

Best regards.

**Comment by RalfJung** [comment]
I can confirm this. For now, you can use <http://play.integer32.com/> where MIR display still works (you have to first select "nightly").

**Comment by Songbird0** [comment]
> For now, you can use http://play.integer32.com/ where MIR display still works

It works, thanks!

**Comment by nodakai** [comment]
#284 had a typo in MIR output formatting

**Comment by mbrubeck** [comment]
Filed #290.
