### ISSUE TITLE
Support testing

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-playpen#32]
A rustbyexample [testing example](http://rustbyexample.com/staging/test.html) is below. It would be cool if you could click **Run** or **Test** in the playpen when there is a test to be run.

```rust
fn distance(a: (f32, f32), b: (f32, f32)) -> f32 {
    (
        (b.val0().powi(2) - a.val0().powi(2)) +
        (b.val1().powi(2) - a.val1().powi(2))
    ).sqrt()
}

fn main() {
    println!("If you see this, the tests were not compiled nor ran!");
}

#[test]
fn distance_test() {
    assert!(distance((0f32, 0f32), (1f32, 1f32)) == (2f32).sqrt());
}
```

**Comment by ranma42** [comment]
I have written the changes that should be sufficient to enable testing and benchmarking (and I will PR as soon as I manage to test them). I think this would be pretty convenient as it would make the playpen a place to reproduce behaviours mentioned in Rust PR/issues by simply pasting the code in the playpen. I can see that passing arbitrary command line arguments might be interesting, but I'm afraid of the input validation.
@thestinger Any suggestions on how to tackle this?

**Comment by cristicbz** [comment]
AFAICT @chris-morgan's PR doesn't deal with benchmarks. Would be really nice if the playpen supported that, allowing people to share microbenches.

**Comment by alexcrichton** [comment]
I believe this was done awhile back
