### ISSUE TITLE
Design Revamp

### ISSUE THREAD

**Issue by Ap0ph1s** [rust-lang/rust-playpen#70]
Just a suggestion, we should make playplayen a bit more appealing to new users, sort of like a sublime text theme :P

**Comment by welbornprod** [comment]
Ace has plenty of themes builtin already. Using `ace/ext-themelist.js` it's trivial to have a dropdown combo theme selector. I prefer Solarized Dark so I've already hacked play.rust-lang.org using TamperMonkey and Stylish to accommodate my needs. It would be great if I could just select it from a menu though.

**Comment by Ap0ph1s** [comment]
Thats pretty nice!

**Comment by welbornprod** [comment]
I've made pull request #72 to add theme selection to the playpen.

**Comment by sinistersnare** [comment]
Should this be closed?

**Comment by Ap0ph1s** [comment]
:P
