### ISSUE TITLE
Incorrect highlighting

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-playpen#77]
Code appears red but should not. Due to lifetime 't at the end.

http://is.gd/0BZZ2o

**Comment by cjwelborn** [comment]
I forwarded this issue to [Ace](https://github.com/ajaxorg/ace/issues/2394). They've already fixed some problems with the Rust highlighting, and I see some other 'rust-mode' reports on their tracker.

**Comment by steveklabnik** [comment]
:confetti_ball: thanks!

**Comment by cjwelborn** [comment]
Just waiting for the next Ace version now.
