### ISSUE TITLE
SSL Certificate chain is incomplete

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust-playpen#78]
This yields an error in some cases. See https://www.ssllabs.com/ssltest/analyze.html?d=play.rust-lang.org.

It seems the site's certificate is given, but not the certificate for `COMODO RSA Domain Validation Secure Server CA `.

I believe the fix for this is prepending the `COMODO RSA Domain Validation Secure Server CA` certificate given to the site's certificate.

**Comment by alexcrichton** [comment]
Fixed now, thanks for the report!
