### ISSUE TITLE
Add a nightly channel

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-playpen#83]
Maybe `nightly.play.rust-lang.org` or something like that. Or a toggle in the interface but it needs to be linkable to. Rustbyexample uses nightly currently.

**Comment by alexcrichton** [comment]
Done! (version dropdown on the main site)

**Comment by tshepang** [comment]
@alexcrichton there used to be a drop-down for other versions. Why was that  removed?

**Comment by alexcrichton** [comment]
There has only been the option of "master" recently actually, it was just expanded to beta/nightly

**Comment by tshepang** [comment]
I mean what was there months ago

**Comment by alexcrichton** [comment]
That may be why they disappeared, they disappeared three months ago :)

**Comment by tshepang** [comment]
My question is why were other versions dropped (three months ago)?

**Comment by alexcrichton** [comment]
Very little Rust code still works with 0.12.0 and below, so there's not much point to actually keeping them around.
