### ISSUE TITLE
Nightly mode for the bots

### ISSUE THREAD

**Issue by tsion** [rust-lang/rust-playpen#85]
Right now the bots are beta-only, but #83 added support for the nightly channel. It would be nice to have nightly versions of playbot and playbot-mini, either with separate nicknames or some special command. (I admit 4 bots would be a bit much, but it doesn't seem that bad if they are reasonably named.)

We could reintroduce the unstable parts of the bot template removed in #81 for the non-mini nightly version of the bot.

**Comment by alexcrichton** [comment]
Due to the way nightly/beta works, the only benefit I can think of is that `playbot-nightly-mini` would allow you to opt in to features via `#![feature]`, but otherwise they should be basically identical. Did you have some other use cases in mind?

**Comment by tsion** [comment]
Yeah, I guess playbot-nighly-mini may not be that useful.

**Comment by alexcrichton** [comment]
Ok, in that case I'm going to close this for now, but we can always add a bot if we can think of a use case for it!

**Comment by tsion** [comment]
But playbot-nightly is still useful with a bunch of default `#[feature(..)]` in its template. Only -mini is not useful.

**Comment by alexcrichton** [comment]
Possibly, yeah, but we're we're likely to not update this template very often and the set of features is likely to change quite often, so I suspect it may not work out well in the long run.
