### ISSUE TITLE
Output panel obscures code view without being able to scroll

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust-playpen#95]
When the output panel is open, it overlays a large portion of the code view without making the code view smaller, so you could scroll it to see the rest of the code. Instead, you have to close the output panel before you can view the obscured code.

Not sure if this is fixable with the current visual design, but one thing that would alleviate it is being able to close the output panel with the Esc key instead of having to break your flow and use the mouse to click 'x' to close it.

Here is a picture that shows the problem:
![](http://i.imgur.com/RigBALy.png)

**Comment by huonw** [comment]
cc @chris-morgan

**Comment by chris-morgan** [comment]
This was a bug that didn’t seem to show up in Firefox and I hadn’t tested that aspect of it properly in Chromium. I have prepared a fix in #96.

**Comment by crumblingstatue** [comment]
@chris-morgan 
Yes, I was using Chromium, which I forgot to mention.

However, I tested it on Firefox 38.0 and the same thing happens.

**Comment by chris-morgan** [comment]
Actually, one variant of the problem I did finally see in Firefox, though it didn’t appear to be happening all the time, while another variant of the problem didn’t happen in Firefox. Anyway, this fixes all variants of the problem completely.

**Comment by crumblingstatue** [comment]
@chris-morgan 
I tried the updated version hosted on chrismorgan.info, and I can confirm it fixes the problem for both Chromium and Firefox.
